package credential_store;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;


@Controller    // This means that this class is a Controller
@RequestMapping(path="/credentials") // This means URL's start with /credentials (after Application path)
public class MainController {
    @Autowired // This means to get the bean called ServiceCredentialsRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CredentialRepository credentialRepository;

    @GetMapping(path="/")
    public @ResponseBody Iterable<CredentialSummaryDTO> getAllServiceCredentials() {
        List<CredentialSummaryDTO> allCredentialSummaries = new ArrayList<>();
        Iterable<Credential> allCredentials = credentialRepository.findAll();

        for (Credential credential : allCredentials) {
            allCredentialSummaries.add(new CredentialSummaryDTO(credential.getId(), credential.getServiceName(),
                    credential.getDateLastModified(), credential.getActive()));
        }
        return allCredentialSummaries;
    }

    @GetMapping(path="/{id}")
    public @ResponseBody CredentialDTO getServiceCredentialsById(@PathVariable Integer id) {
        Credential credential = credentialRepository.findById(id).orElseThrow(() -> new CredentialsNotFoundException(id));
        return new CredentialDTO(credential.getId(), credential.getServiceName(), credential.getEncryptedPassword(),
                credential.getDateLastModified(), credential.getActive());
    }

    @PostMapping(path="/")
    public @ResponseBody
    Credential addNewServiceCredentials(@RequestBody Credential newCredential) {
        // This returns a JSON or XML with the ServiceCredentials
        newCredential.setDateLastModified(Instant.now().toEpochMilli());
        return credentialRepository.save(newCredential);
    }

    @DeleteMapping("/{id}")
    public @ResponseBody
    Credential deleteServiceCredentials(@PathVariable Integer id) {
        Credential retCredential;
        Optional<Credential> optCredential = credentialRepository.findById(id);
        if (optCredential.isPresent()) {
            retCredential = optCredential.get();
            credentialRepository.deleteById(retCredential.getId());
        } else {
            retCredential = new Credential();
        }
        return retCredential;
    }
}
